# Generated by Django 3.1.7 on 2021-03-15 14:40

from django.db import migrations, models
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hashed_id",
                    hashid_field.field.HashidField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("code", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("population", models.IntegerField()),
                ("average_age", models.DecimalField(decimal_places=2, max_digits=5)),
                ("district_code", models.IntegerField()),
                ("department_code", models.IntegerField()),
                ("region_code", models.IntegerField()),
                ("region_name", models.CharField(max_length=100)),
            ],
        ),
    ]
