# Generated by Django 3.1.7 on 2021-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("town", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="town",
            name="hashed_id",
        ),
        migrations.AlterField(
            model_name="town",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
